-- files donations_staging and donors_staging are mock lists generated by Claude AI 
-- showing examples of joins and then specific strategies

-- showing all data in original table
SELECT *
FROM donors;

-- duplicate table as to not work with raw data
CREATE TABLE donors_staging
LIKE donors;

-- insert data into new, duplicated table
INSERT donors_staging
SELECT *
FROM donors;

-- run it and confirm duplicated table shows all data correctly
SELECT *
FROM donors_staging;

-- join separate file of donations on donor_id for full picture of giving
-- this is shows as grouped by donor first and last name
SELECT *
FROM donors_staging
JOIN donations_staging ON donors_staging.donor_id = donations_staging.donor_id
;

-- you can optionally create a new table here rather than join more than once

-- target one-time gifts to convert to recurring
SELECT *
FROM donors_staging
JOIN donations_staging ON donors_staging.donor_id = donations_staging.donor_id
WHERE frequency = "one-time";
-- returns 10 donors
-- strategy: cultivate relationship with these donors to give recurring

-- identify any follow up "none" fields to target for thank you
SELECT donor_id, first_name, last_name, follow_up_dates, follow_up_frequency
FROM donors_staging
WHERE follow_up_frequency = "none";
-- returns names and info for 7 donors to target for follow up cadence

-- identify donors who gave over a certain amount for targeted asks 
SELECT *
FROM donors_staging
JOIN donations_staging ON donors_staging.donor_id = donations_staging.donor_id
WHERE amount >= 500
;
-- can change the amount 
-- strategy: $500+ for a benchmark of targeting major gifts

-- can also use a similar amount-bound query to raise the giving amount
SELECT *
FROM donors_staging
JOIN donations_staging ON donors_staging.donor_id = donations_staging.donor_id
WHERE amount >= 50 AND amount <=250;
-- strategy: these are your donors you can ask to raise their gift by $5, $10, $25, etc.

